metadata_partition_name: "outbreak"
metadata_1_header: "organism"
metadata_2_header: "subtype"
metadata_3_header: "country"
metadata_4_header: "serovar"
metadata_5_header: "age"
metadata_6_header: "date"
metadata_7_header: "source"
metadata_8_header: "special"
